In [1]:
import numpy as np

In [2]:
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

In [4]:
print("Task 1:")
print(f"Shape of data: {data.shape}")

mean_per_station = data.mean(axis=1)
print(f"Mean temperature per station: {mean_per_station}")
print("-" * 30)

Task 1:
Shape of data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]
------------------------------


In [5]:
print("Task 2:")
high_temps = data[data > 28.0]
print(f"Readings above 28.0°C: {high_temps}")
print("-" * 30)

Task 2:
Readings above 28.0°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]
------------------------------


In [6]:
print("Task 3:")
d_min = data.min()
d_max = data.max()

normalized = (data - d_min) / (d_max - d_min)

print("Normalized Data (rounded to 2 decimal places):")
print(np.round(normalized, 2))

Task 3:
Normalized Data (rounded to 2 decimal places):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
